//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeliGider_WPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gelirler
    {
        public int ID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> GelirTipiID { get; set; }
        public string GelirAciklama { get; set; }
        public Nullable<System.DateTime> GelirTarihi { get; set; }
        public Nullable<decimal> GelenPara { get; set; }
    
        public virtual GelirTipleri GelirTipleri { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
