//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeliGider_WPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GelirTipleri
    {
        public GelirTipleri()
        {
            this.Gelirlers = new HashSet<Gelirler>();
        }
    
        public int ID { get; set; }
        public string GelirTipi { get; set; }
    
        public virtual ICollection<Gelirler> Gelirlers { get; set; }
    }
}
