//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeliGider_WPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiderTipleri
    {
        public GiderTipleri()
        {
            this.Giderlers = new HashSet<Giderler>();
        }
    
        public int ID { get; set; }
        public string GiderTipleri1 { get; set; }
    
        public virtual ICollection<Giderler> Giderlers { get; set; }
    }
}
