//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeliGider_WPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giderler
    {
        public int ID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> GiderTipiID { get; set; }
        public string GiderAciklama { get; set; }
        public Nullable<System.DateTime> GiderTarihi { get; set; }
        public Nullable<decimal> GidenPara { get; set; }
    
        public virtual GiderTipleri GiderTipleri { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
