//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeliGider_WPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public Kullanicilar()
        {
            this.Gelirlers = new HashSet<Gelirler>();
            this.Giderlers = new HashSet<Giderler>();
        }
    
        public int ID { get; set; }
        public string kadi { get; set; }
        public string sifre { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string g_soru { get; set; }
        public string g_cevabı { get; set; }
        public string adsoyad { get; set; }
        public string fotograf { get; set; }
    
        public virtual ICollection<Gelirler> Gelirlers { get; set; }
        public virtual ICollection<Giderler> Giderlers { get; set; }
    }
}
