//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeliGider_WPF.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HesapProEntities1 : DbContext
    {
        public HesapProEntities1()
            : base("name=HesapProEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gelirler> Gelirlers { get; set; }
        public virtual DbSet<GelirTipleri> GelirTipleris { get; set; }
        public virtual DbSet<Giderler> Giderlers { get; set; }
        public virtual DbSet<GiderTipleri> GiderTipleris { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
    }
}
